<style type="text/css">
#termsService h4{line-height:30px;margin:40px 0;}
#termsService p{margin:20px 0;}
</style>
<template>
	<div class="textBody" id="termsService">
		<p v-html="termsService"></p>
		<!-- <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Chào mừng bạn đến với Yến Trời !
		Để sử dụng dịch vụ của Yến Trời, bạn nên đọc và tuân thủ “Thỏa thuận dịch vụ của Yến trời” ("Thỏa thuận"). Hãy chắc chắn rằng bạn đã đọc kỹ và hiểu một cách đúng và  đầy đủ về các điều khoản cũng như điều kiện Khi bạn sử dụng dịch vụ của Yến trời thì hành vi đó được coi là bạn đã đọc và đồng ý bị ràng buộc bởi các thỏa thuận trên.
		Nếu bạn dưới 18 tuổi, vui lòng đọc thỏa thuận này cùng một người giám hộ hợp pháp và đặc biệt chú ý đến các điều khoản sử dụng dành cho trẻ vị thành niên.</p>
		<h4>Phạm vi của thỏa thuận</h4>
		<p>1.1 Thỏa thuận này là hợp đồng giữa Người dùng và Yến trời trên trang web YEN (bao gồm nhưng không giới hạn ở www.yenttroi.com, v.v., sau đây được gọi là "Trang web") và các vấn đề liên quan khác. Yến trời có nghĩa là Công ty trách nhiệm hữu hạn công nghệ Yến trời (sau đây gọi tắt là "Công ty Yến trời") và các dịch vụ liên quan của nó có thể tồn tại trong các đơn vị hoạt động liên quan. "Người dùng" nghĩa là người dùng sử dụng các dịch vụ liên quan đến Yến Trời, bao gồm cả người dùng đã đăng ký và người dùng chưa đăng ký và được gọi là bạn trong Thỏa thuận này. Người dùng được yêu cầu đọc kỹ thỏa thuận này trước khi truy cập và đăng ký và sử dụng dịch vụ mạng do "Yến trời cung cấp. Người dùng truy cập hoặc đăng ký và sử dụng dịch vụ do Yến trời cung cấp sẽ được coi là đã đồng ý và chấp nhận các điều khoản của Thỏa thuận này. .Bất kỳ thông báo, quy tắc, thỏa thuận, thông báo công khai, vv trên trang web này được coi là một phần không tách rời của thỏa thuận này. Khi nội dung xung đột với nhau, nội dung pháp lý mới nhất sẽ được áp dụng.</p>
		<p>1.2Các dịch vụ theo Thỏa thuận này đề cập đến internet và các dịch vụ có liên quan được cung cấp bởi trang web yen www.yenttroi.com và các trang web liên quan ("bao gồm nhưng không giới hạn đối với website \ di động \ app \ h5) và các dạng dịch vụ mạng khác, bao gồm nhưng không giới hạn đối với nhắn tin tức thời, phương tiện trực tuyến, giá trị gia tăng trên Internet, thương mại điện tử và các sản phẩm và dịch vụ quảng cáo (sau đây gọi là" dịch vụ ").</p>
		<p>1.3 Chú thích thêm về dịch vụ Yến trời: Yến trời không chịu trách nhiệm về các vấn đề do các dịch vụ dành riêng cho người dùng, nhưng Yến Trời sẽ cố gắng hết sức để hỗ trợ người dùng đàm phán với nhà cung cấp dịch vụ liên quan, những trường hợp không thể đàm phán thì người dùng có thể liên hệ trực tiếp với hiệp hội người tiêu dung, khiếu nại hoặc giải quyết thông qua các kênh hợp pháp.</p>
		<p>1.4Yến Trời không chịu trách nhiệm về gián đoạn dịch vụ mạng hoặc các lỗi khác do bất khả kháng hoặc các lý do không kiểm soát được, nhưng sẽ cố gắng giảm thiểu những tổn thất và những tác động gây ảnh hưởng cho người dùng. Yến trời bảo vệ quyền riêng tư của người dùng và giữ bí mật thông tin cá nhân của người dùng, không tiết lộ cho bên thứ ba nếu không có sự đồng ý của người sử dụng, trừ trường hợp pháp luật có quy định khác. Người dùng tự nguyện đăng ký thông tin cá nhân và tất cả thông tin do người dùng cung cấp tại thời điểm đăng ký là tự nguyện và người dùng có quyền từ chối cung cấp thông tin đó .Yến trời bảo vệ nghiêm ngặt quyền riêng tư của người dùng và giữ bí mật thông tin cá nhân của người dùng trực tuyến, không tiết lộ cho bên thứ ba mà không có sự đồng ý của người dùng trực tuyến, trừ trường hợp pháp luật có quy định khác. Điều này dựa trên nguyện vọng của người sử dụng và người sử dụng có quyền từ chối cung cấp thông tin đó bất cứ lúc nào.</p>
		<p>1.5 Trong tất cả nội dụng trên website của Yến trời không phán ảnh bất kì quan điểm cũng như ý kiến của YEN.</p>
		<p>1.6 Các qui định miễn trách nhiệm YEN sử dụng được qui định bởi luật pháp nhà nước xã hội chủ nghĩa Việt Nam.</p>
		<h4>Những điều cần biết về dịch vụ</h4>
		<p>2.1 YEN thông qua mạng xã hội quốc tế cung cấp mạng lưới dịch vụ. Đồng thời, người sử dụng phải: </p>
		<p>Tự trang bị thiết bị để truy cập mạng, bao gồm máy tính cá nhân, modem hoặc các thiết bị truy cập Internet khác;</p>
		<p>2.2 Dựa trên tầm quan trọng của các dịch vụ mạng được cung cấp bởi trang web này, bạn nên xác nhận</p>
		<p>(1) Cung cấp thông tin đăng ký là đúng, chính xác, đầy đủ, hợp lệ, thông tin đăng ký có thể thay đổi, nên được cập nhật; Sau khi đăng ký thành công, YEN sẽ giúp thiết lập một tài khoản, bạn có thể đặt mật khẩu tương ứng, và trong tất cả các hành vi thực hiện trên tài khoản và mật khẩu đều phải chịu trách nhiệm pháp lý đầy đủ. Bạn không được chuyển nhượng hoặc cho phép người khác sử dụng tài khoản YEN của bạn dưới bất kỳ hình thức nào. Bạn không nên sử dụng tài khoản của người khác để truy cập và chấp nhận các dịch vụ có liên quan với YEN. Bạn nên thông báo cho YEN ngay lập tức nếu mật khẩu hoặc tài khoản của bạn đã được sử dụng mà không được phép hoặc nếu có bất kỳ vấn đề bảo mật nào khác. Sau khi hoàn tất đăng ký, bạn chỉ có thể có quyền sử dụng tài khoản liên quan và bạn không được chuyển nhượng, thuê hoặc tặng tài khoản cho bất kỳ bên thứ ba nào.</p>
		<p>(2) Theo các quy định có liên quan của "Luật an ninh mạng của Cộng hoà xã hội chủ nghĩa Việt Nam", thông tin đăng ký người dùng phải là thông tin thực sự của người đó và chịu trách nhiệm về tính xác thực của thông tin. Bạn nên duy trì và cập nhật thông tin người dùng cá nhân của mình để đảm bảo rằng thông tin đó là đúng, chính xác, hiện tại và đầy đủ. Nếu bạn cung cấp bất kỳ thông tin sai sự thật, không chính xác, quá hạn hoặc không đầy đủ, và để xác định YEN có căn cứ hợp lý để nghi ngờ rằng thông tin đó là không đúng sự thật, không chính xác, quá hạn hoặc không đầy đủ, YEN có quyền tạm dừng hoặc chấm dứt Tài khoản của bạn tại YEN và từ chối sử dụng toàn bộ hoặc một phần dịch vụ của bạn ngay bây giờ và trong tương lai.</p>
		<p>(3) Việc truy cập, đăng ký, sử dụng, vv đại diện cho sự đồng ý đầy đủ của bạn với Thỏa thuận này, có nghĩa là bạn có thể tự chịu trách nhiệm pháp lý để xác nhận rằng bạn có các quyền và khả năng thích hợp để hưởng các dịch vụ của Trang web, thực hiện các cuộc hẹn cho các dịch vụ và giao dịch. Bạn xác nhận rằng nếu bạn dưới 18 tuổi, bạn chỉ có thể sử dụng Trang web với sự tham gia của cha mẹ hoặc người giám hộ khác. </p>
		<p>(4) YEN có quyền từ chối dịch vụ, đóng tài khoản người dùng, xóa hoặc chỉnh sửa nội dung hoặc hủy cuộc hẹn, chỉ trong phạm vi qui định trong giời hạn YEN cho phép. YEN có quyền sửa đổi hoặc ngừng dịch vụ và không chịu trách nhiệm cho người dùng hoặc bất kỳ bên thứ ba nào không liên quan trực tiếp.</p>
		<h4>Cung cấp dịch vụ theo hiện trạng</h4>
		<p>3.1 Người dùng hiểu và đồng ý rằng các dịch vụ của YEN được cung cấp phù hợp với tình trạng hiện tại của điều kiện kĩ thuật. YEN sẽ làm hết sức mình để cung cấp dịch vụ cho người dùng đảm bảo tính liên tục và bảo mật của dịch vụ, tuy nhiên. YEN không thể thấy trước và ngăn chặn rủi ro pháp lý, kỹ thuật và cácvrủi ro khác bất kỳ lúc nào, bao gồm nhưng không giới hạn những lý do bất khả kháng, vi rút, trojan, hack, hệ thống không ổn định, các gián đoạn dịch vụ, mất dữ liệu và các tổn thất và rủi ro khác có thể phát sinh từ các dịch vụ của bên thứ ba, các hoạt động của chính phủ, v.v.</p>
		<h4>Quảng cáo</h4>
		<p>4.1 Bạn đồng ý rằng YEN có thể trong quá trình cung cấp Dịch vụ, gửi cho bạn các quảng cáo, khuyến mãi hoặc thông tin quảng cáo (bao gồm thông tin thương mại và phi thương mại) của chính bạn hoặc của nhà quảng cáo bên thứ ba theo cách thức và phạm vi có thể thay đổi mà không cần thông báo cho bạn.</p>
		<p>4.2 YEN có thể cung cấp cho bạn tính năng tắt thông tin quảng cáo, nhưng bất kỳ lúc nào bạn không thể chặn hoặc lọc thông tin quảng cáo; nhưng không được vi phạm thỏa thuận không rõ ràng hoặc được YEN cho phép một cách rõ ràng.</p>
		<p>4.3 YEN sẽ thực hiện các nghĩa vụ liên quan đến nhà quảng cáo theo các quy định của pháp luật. Bạn sẽ tự đánh giá tính xác thực của thông tin quảng cáo và chịu trách nhiệm vể hành vi của mình. YEN không chịu trách nhiệm cho bất kỳ tổn thất hoặc thiệt hại nào do nội dung quảng cáo gây ra.</p>
		<p>4.4 Bạn đồng ý rằng đối với những thông tin quảng cáo xuất hiện trong dịch vụ của YEN bạn nên cân nhắc đánh giá tính xác thực và độ tin cậy và bạn sẽ chịu trách nhiệm về các giao dịch được thực hiện theo thông tin quảng cáo, ngoại trừ được quy định rõ ràng bởi pháp luật.</p>
		<h4>Chính sách riêng tư.</h4>
		<p>5.1 Tôn trọng quyền riêng tư của người dùng là một chính sách cơ bản của YEN. Vì vậy, như là một bổ sung cho việc phân tích dữ liệu đăng ký người dùng, YEN sẽ không tiết lộ, chỉnh sửa dữ liệu đã đăng ký và nội dung mà được lưu trữ khi mà không có sự cho phép của người dùng hợp pháp. Trừ Khi luật pháp yêu cầu thì YEN cần phải tiết lộ thông tin này trong các trường hợp sau đây:</p>
		<p>(1) Tuân thủ các yêu cầu pháp lý liên quan và tuân thủ các thủ tục dịch vụ pháp lý của YEN;</p>
		<p>(2) Duy trì quyền sở hữu nhãn hiệu của YEN;</p>
		<p>(3) Cố gắng bảo vệ quyền riêng tư của người dùng và cộng đồng trong trường hợp khẩn cấp;</p>
		<p>(4) Đáp ứng các yêu cầu khác có liên quan.</p>
		<p>5.2 Bạn hiểu và đồng ý rằng để tạo thuận lợi cho việc sử dụng các dịch vụ của YEN, YEN sẽ lưu trữ thông tin cần thiết để bạn sử dụng, bao gồm nhưng không giới hạn tên thật, giới tính, ngày sinh, địa chỉ, thông tin liên lạc, sổ địa chỉ, album ảnh, lịch , thông tin định vị, v.v. Trừ khi được yêu cầu bởi luật pháp và các quy định, bạn sẽ không tiết lộ hoặc tiết lộ thông tin cá nhân của bạn cho bên thứ ba mà không có sự cho phép của bạn. Yen sử dụng phương thức lưu trữ mã hóa chuyên nghiệp và các phương thức truyền tải để có thông tin liên quan và sử dụng các biện pháp hợp lý để đảm bảo tính bảo mật thông tin cá nhân của người dùng.</p>
		<p>5.3 Bạn hiểu và đồng ý rằng bạn cần phải cung cấp thông tin nhận dạng thực sự trong quá trình đăng ký tài khoản của bạn hoặc sử dụng trang web. YEN sẽ tiến hành xác thực danh tính thực dựa trên số điện thoại di động theo các yêu cầu liên quan của luật pháp và quy định quốc gia. Nếu thông tin bạn cung cấp không đúng sự thật hoặc không đầy đủ, bạn sẽ không thể sử dụng dịch vụ của YEN hoặc bị hạn chế trong quá trình sử dụng và hậu quả xấu sẽ do bạn gây ra.</p>
		<p>5.4 Khi bạn sử dụng một dịch vụ cụ thể trên trang này, dịch vụ có thể có thỏa thuận riêng, quy tắc kinh doanh liên quan, v.v. (gọi chung là "thỏa thuận cá nhân") và bạn nên đọc và đồng ý với thỏa thuận riêng có liên quan trước khi sử dụng dịch vụ. Bằng cách sử dụng các dịch vụ cụ thể được mô tả ở trên, bạn được coi là đã đọc và đồng ý chấp nhận thỏa thuận riêng tương ứng.</p>
		<p>5.5 YEN thu thập thông tin về bạn</p>
		<p>(1) Thông tin về việc chia sẻ của bạn được cung cấp bởi các bên quan tâm khác khi sử dụng các dịch vụ của trang web này;</p>
		<p>(2) Việc bạn sử dụng trang web, hệ thống có thể tự động thu thập và ghi lại thông tin kỹ thuật, bao gồm, nhưng không giới hạn, địa chỉ IP, thông tin thực tế vị trí, loại trình duyệt, ngày tháng và thời gian và nhu cầu của bạn. Nếu bạn tải xuống hoặc sử dụng yên hoặc phần mềm khách hàng liên kết hoặc truy cập bằng thiết bị di động, YEN có thể đọc thông tin về vị trí và thiết bị di động của bạn, bao gồm nhưng không giới hạn đối với các kiểu thiết bị, Mã nhận dạng thiết bị, hệ điều hành, độ phân giải, nhà cung cấp dịch vụ viễn thông, vv;</p>
		<p>(3) Khi bạn sử dụng dịch vụ trang web, hoặc trong một trình duyệt, truy cập vào nền tảng YEN , vui lòng không cung cấp thông tin nhạy cảm cá nhân của bạn (như chủng tộc, tôn giáo, đảng phái chính trị, sức khỏe cá nhân và thông tin y tế, khuynh hướng tình dục, vv) YEN không đảm bảo khả năng bị thu thập ngoài ý muốn ;</p>
		<p>(4) Khi bạn sử dụng một số dịch vụ YEN, YEN sẽ thu thập các thông tin cần thiết khác của bạn theo các yêu cầu cụ thể của các dịch vụ liên quan. YEN sẽ được thu thập thông tin theo quy định của pháp luật. Bạn nên đảm bảo tính xác thực của thông tin nhận dạng bạn điền hoặc gửi, nếu không bạn có thể chọn từ chối cung cấp cho bạn các dịch vụ liên quan;</p>
		<p>(5) Ngoài những thông tin trên, để phục vụ tốt hơn bạn và nâng cao chất lượng dịch vụ. YEN có thể thu thập thông tin, bao gồm thông tin được cung cấp khi bạn liên hệ với dịch vụ khách hàng với YEN, câu trả lời của bạn cho câu hỏi được cung cấp bởi YEN. Và thông tin bạn thu thập được khi bạn liên lạc với đối tác YEN.</p>
		<p>5.6 Thông tin được thu thập bởi YEN trong quá trình cung cấp dịch vụ cho bạn được sử dụng cho các mục đích sau:</p>
		<p>(1) Được sử dụng như xác thực, bảo mật, phát hiện gian lận và xác thực người dùng khi YEN cung cấp dịch vụ, đảm bảo an toàn cho các sản phẩm và dịch vụ do YEN cung cấp cho bạn;</p>
		<p>(2) có thể sử dụng thông tin cá nhân của bạn để ngăn chặn và phát hiện các hành vi gây nguy hiểm, bất hợp pháp hoặc vi phạm các thỏa thuận với đồng yên hoặc các chi nhánh, chính sách và quy tắc nền tảng để bảo vệ quyền và lợi ích hợp pháp của bạn và đối tác của bạn;</p>
		<p>(3) Hỗ trợ YEN cải thiện các dịch vụ hiện có và thiết kế các mô hình dịch vụ mới;</p>
		<p>(4) Có thể sử dụng thông tin cá nhân của bạn để liên lạc với bạn, để thông báo cho bạn về tài khoản, cập nhật bảo mật, sản phẩm và dịch vụ của bạn;</p>
		<p>(5) Cung cấp cho bạn nội dung quảng cáo phù hợp hơn với bạn và đáp ứng tốt hơn nhu cầu của bạn, bao gồm thông tin quảng cáo của bên thứ ba;</p>
		<p>(6) Chia sẻ thông tin với các đối tác của Yen theo Chính sách bảo mật này để họ có thể gửi cho bạn thông tin về sản phẩm và dịch vụ của họ. Nếu bạn không quan tâm đến nội dung được đề nghị bởi yen, vui lòng trả lời thông báo về nội dung hủy trong thời gian;</p>
		<p>(7) Nâng cấp chứng nhận và quản lý phần mềm;</p>
		<p>(8) yen có thể kết hợp thông tin từ một dịch vụ với thông tin từ các dịch vụ khác để cung cấp cho bạn cách sử dụng dịch vụ được cá nhân hóa và chính xác hơn;</p>
		<p>(9) Cho phép bạn tham gia vào các điều tra đánh giá các sản phẩm và dịch vụ của YEN;</p>
		<p>(10) YEN sẽ không được cung cấp cho bất kỳ bên thứ ba không liên quan, bán, thuê hay chia sẻ thông tin của bạn trừ khi có sự đồng ý trước của bạn, hoặc các bên bên thứ ba mà YEN liên quan .Trong thời gian thực hiện dịch vụ, bên thứ ba sẵn sàng đảm nhận trách nhiệm bảo mật giống như YEN, đồng thời, sau khi dịch vụ kết thúc, bên thứ ba sẽ không thể truy cập tất cả thông tin.</p>
		<p>5. 7 YEN sẽ đảm bảo rằng không tiết lộ hoặc cung cấp thông tin đăng ký của bạn cho bên thứ ba cùng với nội dung không công khai được lưu trữ trong YEN khi bạn sử dụng Dịch vụ và trang web, ngoại trừ trong các trường hợp sau:</p>
		<p>(1) Bạn đã nhận được sự đồng ý hoặc ủy quyền trước;</p>
		<p>(2) Chia sẻ với một bên thứ ba hợp tác với YEN để cung cấp cho bạn các dịch vụ liên quan, với điều kiện bên thứ ba đồng ý chịu trách nhiệm tương tự để bảo vệ quyền riêng tư của người dùng là YEN;</p>
		<p>(3) Chia sẻ với các nhà tài trợ bên thứ ba, những người chọn quảng cáo hoặc thử nghiệm sự kiện;</p>
		<p>(4) Để tuân thủ luật áp dụng hiện hành hoặc các nghĩa vụ pháp lý khác, hoặc nếu bạn vi phạm các luật và quy định liên quan hoặc các thỏa thuận liên quan đến YEN, bạn cần tiết lộ cho bên thứ ba;</p>
		<p>(5) Vì lợi ích công cộng hoặc với các yêu cầu của cơ quan có thẩm quyền của chính phủ;</p>
		<p>(6) Để bảo vệ quyền lợi, hoạt động hoặc tài sản của bạn, nhân viên của YEN và những người dùng hoặc cá nhân khác;</p>
		<p>(7) Để điều tra, ngăn chặn hoặc đối phó với các hoạt động bất hợp pháp tiềm năng hoặc có liên quan, gian lận và các mối đe dọa chống lại an toàn cá nhân, hoặc vi phạm các điều khoản và điều kiện của nền tảng YEN;</p>
		<p>(8) Đảm bảo thỏa thuận dịch vụ người dùng của YEN và thực hiện các thỏa thuận khác giữa YEN hoặc người dùng với tư cách là một bên;</p>
		<p>(9) Chia sẻ với các bên liên quan đến yên nếu pháp luật cho phép;</p>
		<p>(10) Vì mục đích lợi ích công cộng, và sẽ không gây hại lớn cho lợi ích của bạn;</p>
		<p>(11) Nếu bạn là người khiếu nại về tài sản trí tuệ đủ điều kiện và đã đệ đơn khiếu nại, nó phải được tiết lộ cho người trả lời theo yêu cầu của người khiếu nại để cả hai bên có thể xử lý các tranh chấp quyền có thể;</p>
		<p>(12) Hoàn thành việc sáp nhập, chia, mua hoặc chuyển nhượng tài sản;</p>
		<p>(13) Các trường hợp khác mà bạn đồng ý hoặc cần cung cấp dịch vụ cho bạn tốt hơn.</p>
		<p>5.8 Thắc mắc và thay đổi thông tin</p>
		<p>(1) Khi bạn sử dụng dịch vụ YEN, YEN sẽ cố gắng đảm bảo việc truy cập thông suốt và thuận tiện. Nếu thông tin của bạn là không chính xác hoặc có vi phạm pháp luật có liên quan và các quy định, các quy tắc của nền tảng YEN, YEN sẽ cố gắng cung cấp cho bạn nhiều cách khác nhau để bạn có thể cập nhật hoặc xóa thông tin càng sớm càng tốt ;Ngoại trừ có liên quan đến pháp luật hoặc các yêu cầu kinh doanh hợp pháp phải giữ lại thông tin này;</p>
		<p>(2) Bạn có thể đăng nhập nền tảng yên sửa đổi thông tin cá nhân của bạn, cập nhật hoặc truy vấn, nếu bạn nghĩ rằng YEN có dấu hiệu vi phạm pháp luật và các quy định có liên quan, hoặc vi phạm các thỏa thuận sử dụng, thu thập, lưu trữ thông tin cá nhân của bạn, bạn có thể sử dụng dịch vụ chắm sóc khách hàng liên lạc với YEN . Chỉnh sửa, cập nhật hoặc thay đổi thông tin cá nhân của bạn, YEN sẽ được yêu cầu xác minh danh tính của bạn, và sau đó quyết định xem có nên xử lý yêu cầu của bạn dựa trên các kết quả xác minh. YEN bảo lưu quyền từ chối yêu cầu bạn do cần sử dụng quá nhiều phương tiện kỹ thuật hoặc có thể gây rủi ro cho thông tin cá nhân của người dùng khác;</p>
		<p>(3) Bạn hiểu và đồng ý: YEN sẽ được truy cập và sửa đổi thông tin cá nhân để cung cấp hỗ trợ cho bạn dựa trên phương tiện kỹ thuật phổ biến, và YEN sẽ được dựa trên các trường hợp khác nhau mà cung cấp sự hỗ trợ trên, nhưng không loại trừ, khi cần thiết cho việc hỗ trợ nêu trên được tính phí. YEN sẽ cố gắng bảo vệ thông tin của bạn khỏi những thiệt hại bất khả kháng hoặc những ý đồ không tốt . Khi bạn xóa thông tin cá nhân từ n nền tảng dịch vụ, YEN có thể không được gỡ bỏ ngay lập tức các bản sao còn lại của thông tin từ máy chủ sử dụng, hoặc có thể không xóa các thông tin từ hệ thống sao lưu.</p>
		<p>5.9 Bảo vệ thông tin</p>
		<p>(1) Yên sẽ lưu trữ thông tin cá nhân của bạn theo thỏa thuận và quy định có liên quan trong phạm vi của Chính sách bảo mật này. YEN sẽ sử dụng các biện pháp hợp lý và phương tiện kỹ thuật để bảo vệ thông tin cá nhân của bạn  tránh bị rò rỉ, hư hỏng hoặc mất, bao gồm nhưng không giới hạn lưu trữ mã hóa thông tin, truyền mã hóa thông tin, kiểm soát truy cập trung tâm dữ liệu, v.v.</p>
		<p>(2) YEN cũng quản lý chặt chẽ nhân viên hoặc bên thứ ba có thể tiếp xúc với thông tin của bạn, bao gồm nhưng không giới hạn ký các thỏa thuận bảo mật và thiết lập các hệ thống bảo mật liên quan;</p>
		<p>(3) Bạn nên giữ tài khoản và mật khẩu và các thông tin liên quan khác. YEN sẽ đảm bảo rằng thông tin của bạn không bị mất, bị lạm dụng và thay đổi bởi các biện pháp bảo mật như sao lưu vào các máy chủ khác và mã hóa mật khẩu người dùng. Mặc dù các biện pháp an ninh nói trên, do hạn chế kỹ thuật và phương tiện, ngay cả khi bạn làm mọi thứ có thể để tăng cường các biện pháp an ninh, thì cũng sẽ không có "biện pháp bảo mật hoàn hảo" trên mạng thông tin. Nếu bạn đã để thông tin tài khoản và mật khẩu của mình bị rò rỉ do các lý do của riêng bạn, bạn sẽ chịu trách nhiệm về mặt pháp lý ;</p>
		<p>(4) Bạn hiểu và đồng ý : Bạn sử dụng trang web của YEN, nếu bạn không tránh khỏi việc phải tiết lộ hoặc cung cấp thông tin cá nhân của bạn với đối tác tiềm năng hay các đối tác khác, và bạn nên có sự bảo vệ tốt trong trường hợp cần thiết. Bạn sử dụng YEN trong nền tảng dịch vụ, nếu bạn phát hiện thông tin cá nhân của bạn đã bị xâm nhập hoặc các trường hợp có thể đã bị xâm nhập, bạn nên liên hệ DỊch vụ Khách hàng của YEN. Để YEN có thể có các biện pháp hiệu quả để đảm bảo sự an toàn cho thông tin cá nhân của bạn, tránh tài thiệt hại cho tài khoản của bạn, ngăn chặn sự xuất hiện và gia tăng hơn nữa của sự mất mát. Cho dù YEN đã đưa phương tiện hiệu quả để ngăn chặn sự thiệt hại của bạn hoặc ngăn chặn thiệt hại của bạn gia tăng. YEN sẽ không chịu bất cứ trách nhiệm đối với thiệt hại của bạn, Bạn hoàn toàn chịu trách nhiệm về những thiệt hại này.</p>
		<h4>Lưu trữ và hạn chế thông tin của người sử dụng </h4>
		<p>6.1 YEN sẽ không chịu trách nhiệm với những thông tin mà người sử dụng đăng tải bị lỗi khi lưu hoặc xoá dữ liệu. YEN có quyền xác định xem hành vi của người dùng có tuân thủ các yêu cầu và tinh thần của Điều khoản Thoả thuận dịch vụ của YEN hay không.Nếu người dùng vi phạm các điều khoản dịch vụ, YEN có quyền ngừng cung cấp dịch vụ mạng của mình.</p>
		<h4>Từ chối cung cấp dịch vụ bảo hành</h4>
		<p>Trừ những trường hợp đã được xác nhận bằng văn bản, YEN không Yen có quyền xác định xem hành vi của người dùng có tuân thủ các yêu cầu và tinh thần của Điều khoản dịch vụ của đồng yên hay không.Nếu người dùng vi phạm các điều khoản của dịch vụ, yên có quyền ngừng cung cấp dịch vụ mạng của mình.</p>
		<h4>Hệ thống bảo hành </h4>
		<p>8.1 Hệ thống an ninh là một hệ thống đảm bảo dịch vụ được thiết lập và khởi xướng bởi YEN để bảo vệ quyền lợi hợp pháp của bạn. công ty trang trí cung cấp dịch vụ bảo hành cho người tiêu dùng trong phạm vi cam kết. </p>
		<p>8.2 DỊch vụ “Thi công trước trả tiền sau"đảm bảo là YEN hoặc những bên liên quan được chỉ định bởi YEN và những công ty thiết kế thi công sử dụng dịch vụ uỷ thác tài chính, công thi thiết kết có thể tiến hành thi công trước, sau khi hoàn thành, YEN hoặc những bên liên quan được chỉ định bởi YEN sẽ trả tiền theo chỉ thị của bạn. </p>
		<p>8.3 Công ty thiết kế thi công trên nền tảng YEN sẽ bồi thường mọi tổn thất cho bạn nếu họ vi phạm nội dung đã cam kết trong thời gian cung cấp dịch vụ cho bạn.</p>
		<p>8.4 YEN không đảm bảo những cam kết của công ty thiết kế thi công, đồng thời cũng không đảm bảo nội dung của các dịch vụ khác ngoại trừ cam kết dịch vụ trên.</p>
		<h4>Xử lý khiếu nại với bên thứ 3 việc người sử dụng đăng tải, phát nội dung</h4>
		<p>9.1 Nội dung bạn đăng tải hoặc phát tán thông qua dịch vụ này (bao gồm nhưng không giới hạn ở các trang web, văn bản, hình ảnh, âm thanh, video, đồ họa, v.v.) thuộc trách nhiệm của bạn.</p>
		<p>9.2 Nội dung bạn đăng tải hoặc phát tán phải có nguồn gốc hợp pháp, những nội dung liên quan phải thuộc quyền sở hữu của bạn hoặc bạn được phép sử dụng.</p>
		<p>9.3 Bạn đồng ý YEN có thể sử dụng nội dung bạn đăng tải hoặc phát tán cho mục đích hoàn thành Thỏa thuận này hoặc cung cấp Dịch vụ.</p>
		<p>9.4 Nếu YEN nhận được thông báo từ chủ sở hữu rằng nội dung bạn gửi hoặc phát tán vi phạm các quyền liên quan, bạn đồng ý rằngYEN có quyền đưa ra phán quyết độc lập và thực hiện các biện pháp như xóa, chặn hoặc phá vỡ liên kết.</p>
		<p>9.5 Bạn không được vi phạm các qui định của pháp luật, hay xâm phạm quyền hợp pháp của người khác khi sử dụng dịch vụ này. Bạn hiểu và đồng ý rằng nếu bạn bị người khác khiếu nại về việc vi phạm,hoặc xâm phạm quyền hợp pháp của người khác, bạn phải cung cấp các thông tin cần thiết như chủ đề, thông tin liên hệ và các nội dung liên quan của các bên có liên quan trong tranh chấp với các bên tranh chấp khác hoặc các phòng ban liên quan để giải quyết khiếu nại kịp thời. Giúp việc giải quyết tranh chấp bảo vệ quyền và lợi ích hợp pháp của người khác.</p>
		<h4>Những lý do bất khả kháng và những điều khoản miễn trách nhiệm khác</h4>
		<p>10.1 Bạn hiểu và đồng ý rằng trong quá trình sử dụng Dịch vụ, bạn có thể gặp phải các yếu tố rủi ro bất khả kháng, điều này có thể khiến Dịch vụ bị gián đoạn. Lý do bất khả kháng là một sự việc khách quan không thể lường trước được, và không thể tránh khỏi có tác động đáng kể lên một hoặc cả hai bên, bao gồm nhưng không giới hạn trong thiên tai như lũ lụt, động đất, dịch bệnh và bão, và các sự kiện xã hội như chiến tranh, bất ổn, hành động của chính phủ, v.v. . Trong tình huống trên,YEN sẽ cố gắng hợp tác với các đơn vị liên quan ưu tiên việc sửa chữa kịp thời, nhưng thiệt hại gây ra cho bạn sẽ không nằm trong phạm vi vi phạm của pháp luật.</p>
		<p>10.2 Trong phạm vi luật pháp cho phép, YEN sẽ không chịu trách nhiệm cho việc bị ngừng hoặc gián đoạn dịch vụ nào do:</p>
		<p>(2) Phần mềm, hệ thống, phần cứng và đường truyền thông của người dùng hoặc yên ả bị lỗi;</p>
		<p>(3) Hoạt động người dùng không đúng;</p>
		<p>(4) Người dùng sử dụng dịch vụ thông qua một phương thức không được ủy quyền bằng đồng yên;</p>
		<p>(5) Các trường hợp khác mà yên không thể kiểm soát hoặc được dự đoán hợp lý.</p>
		<p>10.3 Bạn hiểu và đồng ý rằng trong quá trình sử dụng Dịch vụ, bạn có thể gặp phải các rủi ro phát sinh từ thông tin mạng hoặc từ những người dùng khác. YEN sẽ khôgn chịu trách nhiệm đối với tính xác thực, tính hợp lý, tính hợp pháp hoặc đảm bảo trách nhiệm, đồng thời cũng không chịu trách nhiệm cho những thiệt hại bạn gây ra. Những rủi ro này bao gồm nhưng không giới hạn:</p>
		<p>(1) Thông tin có chứa các mối đe dọa, phỉ báng, xúc phạm hoặc bất hợp pháp nội dung từ ẩn danh hoặc mạo danh;</p>
		<p>(2) Bất kỳ sự hiểu lầm, lừa dối hoặc thiệt hại về mặt tâm lý, thể chất hoặc tổn thất kinh tế gây ra hoặc có khả năng gây ra bởi việc sử dụng các dịch vụ theo Hiệp định này;</p>
		<p>(3) Các rủi ro khác do thông tin mạng hoặc hành vi của người dùng gây ra.</p>
		<p>10.4 YEN dựa theo thỏa thuận này để giải quyết xử lý với nội dung vi phạm, quyền này cũng không cấu thành nghĩa vụ hoặc cam kết của YEN, Yen không thể cam kết bảo đảm được viêc phát hiện hoặc xử lý những vi phạm ngay lập tức. </p>
		<p>10.5 Trong tất cả các hoàn cảnh, bạn cũng không nên dễ dàng cho mượn tài khoản, mật khẩu, hoặc những thứ liên quan đến tài sản hoặc thông tin mạng. Khi có giao dịch liên quan đến tài sản, vui lòng xác thực danh tính đối phương, đồng thời thường xuyên lưu ý những tin tức cảnh báo phòng chống tội phạm của YEN.</p>
		<h4>Dịch vụ có hiệu lực và những thay đổi</h4>
		<p>11.1 Bạn sử dụng dịch vụ của YEN được coi là đã đọc và đồng ý với thoả thuận này.</p>
		<p>11.2 YEN bảo lưu quyền sửa đổi bất kỳ điều khoản nào của Thỏa thuận này bất kỳ lúc nào. Khi YEN đã sửa đổi bất kỳ điều khoản nào của Thỏa thuận này, YEN sẽ cung cấp phiên bản mới nhất và liên kết trên trang web. Khi thỏa thuận dịch vụ người dùng của YEN thay đổi, hãy lưu ý và cập nhật thay đổi một cách kịp thời. Nếu bạn không đồng ý với việc sửa đổi thỏa thuận này, hoặc không hài lòng với dịch vụ của YEN, bạn có thể thực hiện các quyền sau: ngừng sử dụng dịch vụ của YEN hoặc, thông qua dịch vụ khách hàng và các kênh khác, yêu cầu YEN ngừng dịch vụ của mình. Khi chấm dứt dịch vụ, quyền sử dụng dịch vụ YEN của người dùng sẽ bị chấm dứt ngay lập tức. Trong trường hợp này, YEN không có nghĩa vụ chuyển bất kỳ thông tin hoặc dịch vụ nào cho người dùng hoặc bất kỳ bên thứ ba nào không liên quan trực tiếp.</p>
		<p>11.3 Sau khi các điều khoản của Thỏa thuận này đã được thay đổi, nếu bạn tiếp tục sử dụng phần mềm hoặc dịch vụ được cung cấp bởi YEN, bạn được coi là đã chấp nhận thỏa thuận sửa đổi. Nếu bạn không chấp nhận thỏa thuận sửa đổi, bạn nên ngừng sử dụng phần mềm hoặc dịch vụ do YEN cung cấp.</p>
		<h4>Thay đổi, tạm ngừng và chấm dứt </h4>
		<p>12.1 YEN có thể tiến hành thay đổi nội dung dịch vụ, cũng có thể sẽ gián đoạn, tạm dừng hoặc chấm dứt dịch vụ</p>
		<p>12.2 Bạn hiểu và đồng ý rằng YEN có quyền xác định chiến lược kinh doanh của riêng mình. YEN có thể chuyển giao một số hoặc tất cả các dịch vụ theo thỏa thuận này cho bên thứ ba để hoạt động hoặc thực hiện sau khi thông báo đơn phương cho bạn. Bên nhận cụ thể phải tuân theo thông báo của YEN.</p>
		<p>YEN có quyền tạm dừng hoặc chấm dứt các dịch vụ được cung cấp cho bạn mà không cần thông báo trong trường hợp có bất kỳ điều nào sau đây:</p>
		<p>(1)Dựa theo luật những thông tin mà bạn cung cấp phải là thông tin thực ;nếu bạn cung cấp thông tin không chính xác cho khi đăng kí, không xác minh được thông tin, hoặc thông tin cá nhân và thông tin đăng kí không đồng nhất sẽ không đươc sử dụng làm bằng chứng hợp pháp.</p>
		<p>(2) Bạn vi phạm các luật và quy định có liên quan hoặc thỏa thuận của thỏa thuận này;</p>
		<p>(3) phù hợp với các quy định của pháp luật hoặc các yêu cầu của cơ quan có thẩm quyền;</p>
		<p>(4) Vì lý do bảo mật hoặc các trường hợp cần thiết khác.</p>
		<p>12.3 YEN có quyền tiến hành việc thu phi nếu hợp đồng kí kết giữa hai bên là hợp đồng dịch vụ có thu phí. Nếu bạn không nộp các khoản thu đúng thời hạn, YEN có quyền gián đoạn, tạm dừng, hoặc chấm dứt cung cấp dịch vụ.</p>
		<p>12.4 Bạn có trách nhiệm sao lưu dữ liệu được lưu trữ trong Dịch vụ. Nếu dịch vụ của bạn bị chấm dứt, bạn có thể xóa vĩnh viễn dữ liệu của mình khỏi máy chủ, trừ khi được luật và quy định yêu cầu khác. Sau khi dịch vụ chấm dứt, YEN không có nghĩa vụ trả lại dữ liệu cho bạn.</p>
		<h4>Quản lý người sử dụng</h4>
		<p>13.1 Người dùng tự chịu trách nhiệm về nội dung đăng tải. Việc sử dụng Dịch vụ của người dùng được áp dụng dựa trên tất cả các tiêu chuẩn pháp lý của địa phương và quốc tế.</p>
		<p>13.2 Người dùng phải tuân theo:</p>
		<p>(1) Khi chuyển thông tin kỹ thuật từ bên trong Việt Nam, nó phải tuân thủ các luật và quy định liên quan của Việt Nam;</p>
		<p>(2) Việc sử dụng các dịch vụ mạng không phải là bất hợp pháp;</p>
		<p>(3) Không can thiệp hoặc làm gián đoạn các dịch vụ mạng;</p>
		<p>(4) Tuân thủ tất cả các giao thức mạng, quy định, thủ tục và thực hành sử dụng dịch vụ mạng.</p>
		<p>(5) Nhắc nhở của bài viết hoặc tải lên tác phẩm thiết kế của người khác với sự đồng ý của tác giả trước và cho biết "tên và nguồn gốc của tác giả gốc, bản quyền chỉ thuộc sở hữu của tác giả gốc" và yên không phải chịu kết quả trực tiếp hoặc gián tiếp về vi phạm có thể. Bất kỳ trách nhiệm nào.</p>
		<p>(6) Người dùng phải cam kết không truyền bất kỳ thông tin bất hợp pháp, quấy rối, vu khống, xúc phạm, đáng sợ, độc hại, thô tục, tục tĩu và thông tin khác. Ngoài ra, người dùng không được phép đăng tải bất kỳ thông tin nào khiến người khác cấu thành một hành động phạm tội, họ không thể truyền tải thông tin góp phần vào điều kiện bất lợi trong nước và an ninh quốc gia, họ không thể truyền tải bất kỳ thông tin nào không tuân thủ các quy định của địa phương, luật pháp quốc gia và luật pháp quốc tế.</p>
		<h4>Quyền lợi</h4>
		<p>14.1 Người dùng có bản quyền và các quyền liên quan theo thông tin pháp lý mà họ tạo và đăng tải trên YEN.</p>
		<p>14.2 Một số dịch vụ của YEN sẽ cho phép người dùng tải lên thông tin (bao gồm nhưng không giới hạn ở bất kỳ văn bản, hình ảnh, âm thanh và video, v.v.) trên nền tảng YEN và các sản phẩm liên quan, và bạn đảm bảo rằng bạn có quyền sở hữu hợp pháp hoặc ủy quyền của thông tin được tải lên và: Khi bạn tải lên thông tin này, bạn cũng không được phép hủy bỏ thông tin này, bao gồm nhưng không giới hạn sao chép, sửa đổi, chỉnh sửa, xuất bản, dịch, phân phối, thực hiện, hiển thị và tạo nội dung phái sinh. Đồng thời, bạn đồng ý rằng YEN sẽ cho phép sử dụng nội dung được đăng bởi người dùng trên trang web này cho đối tác đã ký thỏa thuận hợp tác chính thức và cho biết người dùng và nguồn từ YEN. Nếu bạn không đồng ý với điều khoản nói trên, bạn có thể ngừng tải lên hoặc xóa thông tin đã tải lên.</p>
		<p>14.3 YEN tôn trọng tất cả các quyền và lợi ích hợp pháp của người dùng và duy trì các quyền này. Nếu bạn tuyên bố rằng bất kỳ nội dung hoặc bất kỳ tác phẩm nào được công bố bởi YEN bị đánh cắp hoặc trích dẫn từ người dùng khác và bất kỳ nội dung hoặc công việc nào trên trang web YEN vi phạm bản quyền, nhãn hiệu hoặc các quyền hợp pháp khác của người dùng, vui lòng gửi đơn khiếu nại và cung cấp thông tin liên hệ sau. Bằng chứng về danh tính, giấy chứng nhận quyền sở hữu và chứng nhận vi phạm chi tiết, YEN sẽ có biện pháp tương ứng càng sớm càng tốt. Chi tiết liên hệ của YEN như sau: yenttroi@yenttroi.com.</p>
		<p>14.4 Nội dung do người dùng tải lên không được vi phạm bất kỳ luật và quy định hoặc vi phạm quyền hợp pháp của bất kỳ bên thứ ba nào. YEN không có nghĩa vụ, khả năng giám sát quyền sở hữu, và bản quyền của nội dung do người dùng tải lên. Đồng thời không chịu trách nhiệm về bất kỳ thiệt hại về danh tiếng hoặc tài sản nào do người dùng tải lên thông tin, trừ khi được đồng ý khác hoặc yêu cầu pháp luật và quy định. Bạn nên cung cấp nội dung cho trang web chính xác đảm bảo rằng nội dung được cung cấp là đúng sự thật, đầy đủ, hợp pháp và hiệu quả. Nếu nội dung bạn cung cấp là bất hợp pháp, không đúng sự thật, không chính xác và không đầy đủ, bạn chịu trách nhiệm về hậu quả tương ứng, đồng thời YEN bảo lưu quyền chấm dứt việc sử dụng các dịch vụ của bạn tại trang web này. Nếu bạn bị thiệt hại về kinh tế hoặc có những thiệt hại khác tại YEN, bao gồm nhưng không giới hạn bất kỳ khiếu nại bản quyền nào phát sinh từ hình ảnh bạn đã tải lên YEN, bạn có quyền yêu cầu bồi thường cho tất cả các tổn thất (bao gồm nhưng không giới hạn các khoản phí bồi thường khác nhau, phí pháp lý, phí pháp lý, chi phí đi lại, v.v ...).</p>
		<p>14.5 YEN có quyền tiết lộ thông tin đăng ký của người dùng và việc sử dụng trang web YEN cho cơ quan chính phủ có thẩm quyền hoặc chủ sở hữu quyền khi có yêu cầu hoặc YEN phát hiện người dùng bị nghi ngờ vi phạm quyền sở hữu trí tuệ hoặc các quyền hợp pháp khác.</p>
		<h4>Người dùng có hành vi vi phạm qui định</h4>
		<p>15.1 Bạn phải tuân thủ luật pháp và các quy định khi sử dụng dịch vụ này. Không được sử dụng dịch vụ này để tham gia vào các hoạt động bất hợp pháp, bao gồm nhưng không giới hạn:</p>
		<p>(1) Phát hành, truyền tải, phổ biến và lưu trữ nội dung đe dọa an ninh quốc gia, làm gây bất ổn cho xã hội, vi phạm trật tự công cộng, nói tục, xúc phạm, vu khống, khiêu dâm, bạo lực và vi phạm quy định luật pháp quốc gia;</p>
		<p>(2) xuất bản, truyền tải, truyền tải và lưu trữ nội dung vi phạm các quyền hợp pháp của quyền sở hữu trí tuệ của người khác, bí mật thương mại, vv;</p>
		<p>(3) các sự kiện hư cấu độc hại, che giấu sự thật để lừa dối và đánh lừa người khác;</p>
		<p>(4) Xuất bản, truyền tải và phổ biến thông tin quảng cáo và spam;</p>
		<p>(5) Hành vi bị cấm bởi các luật và quy định khác.</p>
		<p>15.2 Nếu bạn vi phạm thoả thuận này, các cơ quan nhà nước có liên quan có thể nộp đơn kiện, phạt tiền hoặc dùng các biện pháp trừng phạt khác đối với bạn đồng thời yêu cầu trợ giúp từ YEN. Nếu gây ra thiệt hại, bạn phải bồi thường theo pháp luật qui định và YEN sẽ không chịu bất kỳ trách nhiệm nào.</p>
		<p>15.3 Nếu YEN phát hiện hoặc nhận báo cáo từ những người khác cho rằng thông tin của bạn cung cấp có dấu hiệu vi phạm, thì YEN có quyền đưa ra quyết định và sử dụng các phương tiện kỹ thuật để xóa, chặn hoặc ngắt kết nối liên kết. Đồng thời, YEN cũng có quyền thực hiện các biện pháp bao gồm (nhưng không giới hạn) đình chỉ hoặc chấm dứt dịch vụ, hạn chế, đóng băng tài khoản đã đăng ký và truy cứu trách nhiệm pháp lý, tùy thuộc vào bản chất hành vi của người sử dụng </p>
		<p>15.4 Nếu bạn vi phạm Điều này và gây thiệt hại cho bất kỳ bên thứ ba nào, bạn sẽ tự chịu trách nhiệm, nếu bạn chịu tổn thất, bạn cũng sẽ phải bồi thường</p>
		<h4>Qui định và thẩm quyền sử dụng </h4>
		<p>16.1 Việc ban hành, thực thi, giải thích Thoả thuận này và giải quyết tranh chấp sẽ được điều chỉnh bởi Qui định của YEN (không bao gồm xung đột về mặt pháp luật). Trong trường hợp có tranh chấp liên quan đến nội dung hoặc việc thực hiện của Thỏa thuận này, các bên sẽ cố gắng giải quyết tranh chấp thông qua thương lượng hoà giải thân thiện;</p>
		<p>16.2 Nếu bất kỳ điều khoản nào trong thoả thuận được coi là bị thu hồi, không hợp lệ hoặc không thể thi hành vì bất kỳ lý do nào. Điều đó sẽ có thể được coi là phân tách điều khoản và sẽ không ảnh hưởng đến tính hợp pháp và khả năng thực thi của bất kỳ điều khoản nào còn lại.</p>
		<p>16.3 Các quyền khác không rõ ràng trong Thỏa thuận này được bảo lưu bởi Yên và bạn phải được sự cho phép bằng văn bản của Yên để thực hiện các quyền này. Nếu YEN không thực hiện bất kỳ quyền nào nêu trên, thì đồng thời không cấu thành sự từ bỏ quyền đó.</p>
		<p>16.4 Các tiêu đề của tất cả các điều khoản trong thoả thuận này chỉ mang tính tiêu chuẩn và không bao hàm ý nghĩa trên thực tế và không được sử dụng làm cơ sở để giải thích ý nghĩa của Thỏa thuận này.</p>
		<h4>Điều khoản sử dụng đối với người chưa thành niên </h4>
		<p>17.1 Nếu người sử dụng chưa đủ 18 tuổi, gọi tắt là vị thành niên, dưới sự chỉ đạo và giám hộ của người giám hộ, đọc những qui định thoả thuận và sử dụng của dịch vụ này. </p>
		<p>17.2 Người dùng vị thành niên chưa tiếp cận với xã hội nhiều , có thể dễ dàng bị mê hoặc bởi hình ảnh hư cấu của mạng xã hội, cùng với sự hiếu kì. Do đó, trẻ vị thành niên nên chú ý đến các vấn đề sau khi sử dụng dịch vụ này để nâng cao nhận thức về an toàn và tăng cường bảo vệ bản thân mình:</p>
		<p>(1) Nhận biết rõ về sự khác nhau giữa thế giới ảo và thế giớ thực tại, tránh bị mê muội bởi mạng Internet, ảnh hưởng đến công việc học tập hàng ngày.</p>
		<p>(2) Khi điền các thông tin cá nhân, tăng cường ý thức bảo vệ bản nhân, tránh để những thành phần xấu quấy rối cuộc sống.</p>
		<p>(3) Sử dụng mạng Internet đúng đắn, dưới sự chỉ đạo của người giám hộ hoặc thầy cô giáo.</p>
		<p>(4) Tránh tuỳ tiện gặp gỡ những bạn quen trên mạng hoặc tham gia những hoạt động offline, tránh những thành phần phi pháp có cơ hội tận dụng gây nguy hiểm cho bản thân. </p> -->
	</div>
</template>
<script type="text/javascript">
export default {
	name:'',
	components:{
	},
	data(){
		return {
			termsService:'',
		}
	},
	methods:{
		getData:function(){
			this.$fetch('/article/termsData')
			.then((res)=>{
				this.termsService = res.data
			})
		}
	},
	mounted(){
	},
	created(){
		this.getData()
	}
}
</script>